## This playbook is not in use ##
---
- name: Install AWScli on J_Agent
  hosts: Prod
  become: true
  remote_user: ubuntu
  tasks:
    - name: Install AWS CLI
      shell: | 
        sudo apt install unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
        unzip awscliv2.zip
        sudo ./aws/install
## This playbook is not in use ##